// tools-effects.js -- one of 4 files split out of the former tools-common.js
// (2026-08-20, structural item #42: that file had grown to 1,447 lines
// mixing dialogs, media, navigation, and PWA concerns together).
//
// This file: completion celebration, help/info modal content, icon-search
// toggle, row-exit animation, swipe-back-to-workspace gesture, and the
// form-section collapse/expand toggle.
//
// Split was verified lossless before any of these files were touched --
// the 4 pieces were confirmed to concatenate back into a byte-for-byte
// exact copy of the original file before this header (or any of the
// others) was added. Loaded via <script defer> in the same relative
// order the four files' content originally appeared in -- defer
// preserves document order and none of these are wrapped in a module
// scope, so splitting into multiple files changes nothing about
// execution order or what's globally accessible.

// Shared behavior for the internal Workspace tool suite.
// One of 4 files loaded via <script src="/tools/tools-effects.js" defer>
// (along with tools-dialogs.js, tools-media-sharing.js, tools-nav-pwa.js)
// by workspace.html and every tool page that needs them.

// ---------------------------------------------------------------------------
// COMPLETION CELEBRATION -- added 2026-08-16. A brief, tasteful moment for
// completion events (marking a job done, crossing a revenue milestone) --
// small pieces falling from the top of the viewport for ~1.1s, then fully
// removed. Deliberately NOT used for routine actions (saving a form,
// syncing) -- reserved for things worth a small acknowledgment. Respects
// prefers-reduced-motion by skipping the falling pieces entirely and
// showing nothing rather than a static substitute -- a decorative moment
// isn't worth overriding someone's motion preference for.
// ---------------------------------------------------------------------------
function celebrateCompletion() {
  if (typeof document === 'undefined') return;
  if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  const colors = ['#ff8000', '#ffb347', '#d8d8d8', '#6fcf97'];
  const container = document.createElement('div');
  container.setAttribute('aria-hidden', 'true');
  container.style.cssText = 'position:fixed; inset:0; z-index:9999; pointer-events:none; overflow:hidden;';

  const pieceCount = 24;
  for (let i = 0; i < pieceCount; i++) {
    const piece = document.createElement('span');
    const size = 5 + Math.random() * 4;
    const left = Math.random() * 100;
    const delay = Math.random() * 0.15;
    const duration = 0.7 + Math.random() * 0.4;
    const drift = (Math.random() - 0.5) * 60;
    const color = colors[i % colors.length];
    piece.style.cssText =
      'position:absolute; top:-12px; left:' + left + 'vw; width:' + size + 'px; height:' + size + 'px;' +
      'background:' + color + '; border-radius:' + (i % 2 === 0 ? '50%' : '2px') + ';' +
      'opacity:0.9; transform:translateY(0);' +
      'animation:th-confetti-fall ' + duration + 's ease-in ' + delay + 's forwards;' +
      '--th-confetti-drift:' + drift + 'px;';
    container.appendChild(piece);
  }
  document.body.appendChild(container);
  setTimeout(() => container.remove(), 1300);
}

if (typeof document !== 'undefined' && !document.getElementById('thConfettiKeyframes')) {
  const style = document.createElement('style');
  style.id = 'thConfettiKeyframes';
  style.textContent = '@keyframes th-confetti-fall { to { transform: translate(var(--th-confetti-drift), 100vh) rotate(280deg); opacity: 0; } }';
  document.head.appendChild(style);
}

// Small color-coded attribution dot -- blue for Connor, pink for Steve.
// Used anywhere a record shows who last touched it (Job Tracker, Invoice
// Generator, Parts & Reference / Appliance Wiki, Dev Tools). Consolidated
// here on 2026-08-14 -- it used to be copy-pasted separately into all 4
// files, so the color map had to be updated in 4 places if it ever
// changed. Now there's just one. Only renders for a real, known account
// email; anything else gets no dot rather than a wrong guess. `label` is
// an optional verb prefix for the tooltip (e.g. "Last edited by",
// "Generated by") -- omit it for a bare-email tooltip.
const PERSON_DOT_COLORS = {
  'connor@triplehenterprisesllc.biz': '#7ec4ff',
  'steve@triplehenterprisesllc.biz': '#f0a8c8',
};
function personDot(email, label) {
  const color = PERSON_DOT_COLORS[(email || '').toLowerCase()];
  if (!color) return '';
  const safeEmail = typeof escapeHtml === 'function' ? escapeHtml(email) : email;
  const title = label ? (label + ' ' + safeEmail) : safeEmail;
  return '<span style="display:inline-block; width:7px; height:7px; border-radius:50%; background:' + color + '; margin-right:5px; vertical-align:middle;" title="' + title + '"></span>';
}

// Captured once, immediately -- before any button on the page could
// possibly have been clicked yet, since this script is deferred and only
// runs after the whole page has parsed. This means per-section "?"
// bubbles (openInfoModal) can safely reuse the exact same modal element
// as the page's main "How to Use" button, without ever permanently
// overwriting that page's real help content with whatever a bubble
// showed most recently.
let _fullHelpTitle = '';
let _fullHelpBody = '';
(function captureFullHelpContent() {
  const overlay = document.getElementById('helpModalOverlay');
  if (!overlay) return;
  const h3 = overlay.querySelector('h3');
  const body = overlay.querySelector('.help-modal-body');
  _fullHelpTitle = h3 ? h3.innerHTML : '';
  _fullHelpBody = body ? body.innerHTML : '';
})();

function openInfoModal(title, bodyHtml) {
  const overlay = document.getElementById('helpModalOverlay');
  if (!overlay) return;
  const h3 = overlay.querySelector('h3');
  const body = overlay.querySelector('.help-modal-body');
  if (h3) h3.innerHTML = title;
  if (body) body.innerHTML = bodyHtml;
  overlay.classList.add('is-open');
}

// Generic collapsed-icon search: a magnifying-glass button that expands
// into the real search input when tapped, and collapses back to just the
// icon if it loses focus while still empty -- keeps a page's toolbar
// compact until a search is actually wanted, everywhere this pattern is
// used across the app.
function toggleIconSearch(wrapId, forceOpen) {
  const wrap = document.getElementById(wrapId);
  if (!wrap) return;
  const input = wrap.querySelector('input');
  const shouldOpen = forceOpen !== undefined ? forceOpen : !wrap.classList.contains('is-expanded');
  if (shouldOpen) {
    wrap.classList.add('is-expanded');
    if (input) setTimeout(() => input.focus(), 50);
  } else {
    wrap.classList.remove('is-expanded');
  }
}
document.addEventListener('focusout', (e) => {
  const wrap = e.target.closest && e.target.closest('.icon-search');
  if (!wrap) return;
  setTimeout(() => {
    if (wrap.contains(document.activeElement)) return;
    const input = wrap.querySelector('input');
    if (input && !input.value.trim()) wrap.classList.remove('is-expanded');
  }, 120);
});

// Generic collapse/expand for "Add X"-style form sections -- used across
// multiple tool pages so a form starts collapsed and the page opens
// showing actual data first, rather than an empty form.
// Fades and collapses ONE specific row before its underlying data
// actually gets deleted and the list re-renders -- called from a real
// delete-button click, never from a render/filter pass, so this can
// never fire on every keystroke the way animating the whole list would.
// Measures the row's own real height first rather than guessing a fixed
// value, since these rows vary in height (wrapped text, extra fields).
function animateRowExit(rowElement, onComplete) {
  if (!rowElement) { onComplete(); return; }
  const reduceMotion = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reduceMotion) { onComplete(); return; }
  const isTableRow = rowElement.tagName === 'TR';
  // A <tr>'s rendered height is governed by the table layout algorithm,
  // not the normal box model -- max-height doesn't actually shrink a
  // table row's real height the way it does for a div, even though the
  // computed style itself transitions fine. Verified this directly
  // rather than assuming: for a <tr>, fall back to an opacity-only fade
  // instead of a collapse that would look subtly broken (correctly
  // fading, but leaving an empty gap where the row's height should be
  // shrinking) rather than actually smooth.
  if (isTableRow) {
    rowElement.style.transition = 'opacity .22s ease';
    requestAnimationFrame(() => { requestAnimationFrame(() => { rowElement.style.opacity = '0'; }); });
    setTimeout(onComplete, 230);
    return;
  }
  const height = rowElement.scrollHeight;
  rowElement.style.maxHeight = height + 'px';
  rowElement.style.overflow = 'hidden';
  rowElement.style.transition = 'opacity .22s ease, max-height .22s ease, margin .22s ease, padding .22s ease, border-width .22s ease';
  // Two rAFs, not one -- the browser needs to actually paint the
  // starting max-height (the row's real current height) as a distinct
  // frame before the target value changes, or the transition has
  // nothing to animate from and just snaps straight to the end state.
  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      rowElement.style.opacity = '0';
      rowElement.style.maxHeight = '0px';
      rowElement.style.marginTop = '0';
      rowElement.style.marginBottom = '0';
      rowElement.style.paddingTop = '0';
      rowElement.style.paddingBottom = '0';
      rowElement.style.borderWidth = '0';
    });
  });
  setTimeout(onComplete, 230);
}

// Swipe right anywhere on the page navigates back to Workspace, mirroring
// the native "swipe back" gesture already familiar from the rest of the
// phone. Content follows the finger in real time rather than only
// reacting after the gesture ends, and either completes the slide-away
// or springs back smoothly depending on whether the swipe actually
// cleared the threshold -- the same feel as a native back-swipe, not a
// binary "did this count or not" check with no feedback in between.
//
// Skips touches that start inside a <table> (a wide table on a narrow
// phone may need its own horizontal scroll), inside a <canvas> (signing
// a contract means dragging a finger across one, which can easily read
// as a horizontal swipe to this same detector -- without this exclusion,
// an in-progress signature gets silently aborted mid-stroke by a
// navigation neither the code nor the person intended), or while a modal
// is open. The modal case matters mechanically, not just visually:
// applying a transform to body creates a new containing block, which
// breaks position:fixed for every descendant -- an open modal would
// start moving with the page instead of staying fixed to the viewport.
function setupSwipeBackToWorkspace() {
  let touchStartX = 0, touchStartY = 0, touchStartTime = 0;
  let dragging = false, committed = false, visuallyDragged = false;
  const DRAG_ELEMENT = document.body;
  const THRESHOLD = 60;
  const MAX_DRAG = 140; // caps how far content visually follows the finger, even on a much longer drag

  function anyModalOpen() {
    return !!document.querySelector('.help-modal-overlay.is-open');
  }

  document.body.addEventListener('touchstart', (e) => {
    if (e.touches.length !== 1) return;
    touchStartX = e.touches[0].clientX;
    touchStartY = e.touches[0].clientY;
    touchStartTime = Date.now();
    dragging = !(e.target.closest && (e.target.closest('table') || e.target.closest('canvas'))) && !anyModalOpen();
    committed = false;
    visuallyDragged = false;
  }, { passive: true });

  document.body.addEventListener('touchmove', (e) => {
    if (!dragging || !e.touches.length) return;
    // A real signature is usually several separate strokes, lifted and
    // re-touched between letters -- checking only where a stroke started
    // isn't enough, since finger imprecision means any single stroke
    // could start a pixel outside the canvas's exact bounds and still be
    // part of the same signature. Checking continuously here means the
    // moment a drag crosses onto a canvas or table at all, swipe
    // detection cancels immediately, not just when it started there.
    if (e.target.closest && (e.target.closest('canvas') || e.target.closest('table'))) {
      dragging = false;
      DRAG_ELEMENT.style.transition = '';
      DRAG_ELEMENT.style.transform = '';
      DRAG_ELEMENT.style.opacity = '';
      return;
    }
    const dx = e.touches[0].clientX - touchStartX;
    const dy = e.touches[0].clientY - touchStartY;
    if (Math.abs(dx) < Math.abs(dy) * 1.5 || dx < 0) return; // not a rightward, mostly-horizontal drag -- leave scrolling alone
    const clamped = Math.min(dx, MAX_DRAG);
    visuallyDragged = true;
    DRAG_ELEMENT.style.transition = 'none';
    DRAG_ELEMENT.style.transform = `translateX(${clamped}px)`;
    DRAG_ELEMENT.style.opacity = String(1 - (clamped / MAX_DRAG) * 0.35);
  }, { passive: true });

  document.body.addEventListener('touchend', (e) => {
    if (!dragging || !visuallyDragged || !e.changedTouches.length) return;
    dragging = false;
    // Also check where the gesture ended, not just where it started or
    // passed through -- belt-and-suspenders with the touchmove check
    // above, since touchend's target can occasionally differ from the
    // last touchmove's target right at the boundary of an element.
    if (e.target.closest && (e.target.closest('canvas') || e.target.closest('table'))) {
      DRAG_ELEMENT.style.transition = '';
      DRAG_ELEMENT.style.transform = '';
      DRAG_ELEMENT.style.opacity = '';
      return;
    }
    const dx = e.changedTouches[0].clientX - touchStartX;
    const dy = e.changedTouches[0].clientY - touchStartY;
    const elapsed = Date.now() - touchStartTime;
    const isMostlyHorizontal = Math.abs(dx) > Math.abs(dy) * 1.5;
    const isFarEnough = dx > THRESHOLD;
    const isFastEnough = elapsed < 600;

    DRAG_ELEMENT.style.transition = 'transform .22s ease, opacity .22s ease';
    if (isMostlyHorizontal && isFarEnough && isFastEnough) {
      committed = true;
      DRAG_ELEMENT.style.transform = 'translateX(100%)';
      DRAG_ELEMENT.style.opacity = '0';
      setTimeout(() => { window.location.href = '/workspace.html'; }, 220);
    } else {
      DRAG_ELEMENT.style.transform = 'translateX(0)';
      DRAG_ELEMENT.style.opacity = '1';
      setTimeout(() => {
        if (!committed) { DRAG_ELEMENT.style.transition = ''; DRAG_ELEMENT.style.transform = ''; DRAG_ELEMENT.style.opacity = ''; }
      }, 230);
    }
  }, { passive: true });

  // A gesture can be interrupted (an incoming call, switching apps
  // mid-swipe) without ever firing touchend -- without this, content
  // could get stuck permanently dragged partway off-screen.
  document.body.addEventListener('touchcancel', () => {
    if (!dragging || !visuallyDragged) return;
    dragging = false;
    DRAG_ELEMENT.style.transition = 'transform .22s ease, opacity .22s ease';
    DRAG_ELEMENT.style.transform = 'translateX(0)';
    DRAG_ELEMENT.style.opacity = '1';
    setTimeout(() => { DRAG_ELEMENT.style.transition = ''; DRAG_ELEMENT.style.transform = ''; DRAG_ELEMENT.style.opacity = ''; }, 230);
  });
}

function toggleFormSection(id, forceOpen) {
  const el = document.getElementById(id);
  if (!el) return;
  if (forceOpen) el.classList.remove('is-collapsed');
  else el.classList.toggle('is-collapsed');
}

function openHelpModal() {
  openInfoModal(_fullHelpTitle, _fullHelpBody);
}

function closeHelpModal() {
  const overlay = document.getElementById('helpModalOverlay');
  if (overlay) overlay.classList.remove('is-open');
}

document.addEventListener('keydown', (e) => {
  if (e.key !== 'Escape') return;
  const dialogOverlay = document.getElementById('customDialogOverlay');
  if (dialogOverlay && dialogOverlay.classList.contains('is-open')) {
    const cancelBtn = document.getElementById('customDialogCancelAction');
    if (cancelBtn) cancelBtn.click();
    return;
  }
  closeHelpModal();
});

// Shared pull-to-refresh (2026-08-27), extracted from workspace.html's
// original (the first page to have this, tested there with real,
// simulated touch event sequences via Playwright) so every synced tool
// page can get the same gesture with its own render callback, instead
// of duplicating this touch-handling logic per page. Self-injects its
// own indicator element if the page doesn't already have one, matching
// how tools-nav-pwa.js already injects the bottom nav rather than
// requiring markup added to every page by hand.
//
// refreshFn is called after a successful pull-past-threshold release --
// pass whatever function(s) a given page already uses to reload and
// re-render its own synced data (e.g. () => { renderJobs(); renderContacts(); }).
// manualRefreshSync() itself is reused unchanged; it already no-ops
// safely if a page has no #refreshSyncLink button to update.
function setupPullToRefresh(refreshFn) {
  if (typeof refreshFn !== 'function') return;
  // TEMPORARY diagnostic logging (2026-08-27) -- added specifically to
  // find a real, reported bug (zero visual feedback on an iPhone
  // installed to the home screen, confirmed still broken after a full
  // fresh reopen, so not a caching issue) that automated testing with
  // simulated touch events didn't catch. Remove once the real device's
  // actual behavior is confirmed via ?debug=1's on-screen trace panel.
  if (typeof debugTrace === 'function') debugTrace('setupPullToRefresh() called');
  let indicator = document.getElementById('pullToRefreshIndicator');
  if (!indicator) {
    indicator = document.createElement('div');
    indicator.id = 'pullToRefreshIndicator';
    indicator.className = 'pull-refresh-indicator';
    indicator.setAttribute('aria-hidden', 'true');
    indicator.innerHTML = '&#8635;';
    document.body.insertBefore(indicator, document.body.firstChild);
    if (typeof debugTrace === 'function') debugTrace('indicator created fresh');
  } else {
    if (typeof debugTrace === 'function') debugTrace('indicator already existed');
  }
  const THRESHOLD = 70; // px pulled before release actually triggers a refresh
  const MAX_PULL = 100; // caps visual growth even on a much longer pull
  let startY = 0, pulling = false, thresholdCrossed = false, refreshing = false;

  function anyOverlayOpen() {
    // Both real overlay-visibility conventions actually used across
    // this app: .is-open for the shared dialog system
    // (ensureDialogModalExists' overlay.className = 'help-modal-overlay'),
    // .is-shown specifically for the photo lightbox.
    return !!document.querySelector('.help-modal-overlay.is-open, .photo-lightbox-overlay.is-shown');
  }

  document.body.addEventListener('touchstart', (e) => {
    if (typeof debugTrace === 'function') debugTrace('touchstart: refreshing=' + refreshing + ' touches=' + e.touches.length + ' scrollY=' + window.scrollY + ' overlayOpen=' + anyOverlayOpen());
    if (refreshing || e.touches.length !== 1) return;
    // Confirmed via direct testing: window.scrollY > 0 alone was too
    // strict for real mobile use -- even a few pixels of scroll offset
    // (easily caused by minor layout shifts: fonts loading, the fixed
    // bottom nav, the address bar collapsing) silently blocked the
    // gesture from ever engaging at all, with zero visual feedback.
    // A small tolerance (matching the common convention in real pull-
    // to-refresh implementations) treats "basically at the top" the
    // same as "exactly at the top."
    if (window.scrollY > 5 || anyOverlayOpen()) {
      if (typeof debugTrace === 'function') debugTrace('touchstart: bailed on scrollY/overlay check');
      pulling = false; return;
    }
    startY = e.touches[0].clientY;
    pulling = true;
    thresholdCrossed = false;
    indicator.style.transition = 'none';
    if (typeof debugTrace === 'function') debugTrace('touchstart: pulling=true, startY=' + startY);
  }, { passive: true });

  document.body.addEventListener('touchmove', (e) => {
    if (!pulling || refreshing || !e.touches.length) {
      if (typeof debugTrace === 'function' && Math.random() < 0.1) debugTrace('touchmove: SKIPPED (pulling=' + pulling + ' refreshing=' + refreshing + ')');
      return;
    }
    const dy = e.touches[0].clientY - startY;
    if (typeof debugTrace === 'function') debugTrace('touchmove: dy=' + dy);
    if (dy <= 0) {
      // Not an actual downward pull (or scrolled back up past the
      // start point) -- reset visually and stop tracking for the
      // rest of this touch, the same way a native pull-to-refresh
      // cancels if you don't keep pulling down.
      indicator.classList.remove('is-visible');
      indicator.style.setProperty('--pull-progress', '0');
      pulling = false;
      return;
    }
    const progress = Math.min(Math.min(dy, MAX_PULL) / THRESHOLD, 1);
    indicator.classList.add('is-visible');
    indicator.style.setProperty('--pull-progress', String(progress));
    if (progress >= 1 && !thresholdCrossed) {
      thresholdCrossed = true;
      if (typeof haptic === 'function') haptic('light'); // "you've pulled enough, release to refresh"
    } else if (progress < 1 && thresholdCrossed) {
      thresholdCrossed = false;
    }
  }, { passive: true });

  document.body.addEventListener('touchend', async () => {
    if (typeof debugTrace === 'function') debugTrace('touchend: pulling=' + pulling + ' thresholdCrossed=' + thresholdCrossed);
    if (!pulling) return;
    pulling = false;
    indicator.style.transition = '';
    if (thresholdCrossed) {
      refreshing = true;
      indicator.classList.remove('is-visible');
      indicator.classList.add('is-refreshing');
      if (typeof manualRefreshSync === 'function') {
        await manualRefreshSync(refreshFn);
      } else {
        await refreshFn();
      }
      if (typeof haptic === 'function') haptic('success');
      indicator.classList.remove('is-refreshing');
      indicator.style.setProperty('--pull-progress', '0');
      refreshing = false;
    } else {
      indicator.classList.remove('is-visible');
      indicator.style.setProperty('--pull-progress', '0');
    }
  }, { passive: true });
}

