// Shared behavior for the internal Workspace tool suite.
// Loaded by workspace.html and every tool page via <script src="/tools-common.js" defer>.

// Small color-coded attribution dot -- blue for Connor, pink for Steve.
// Used anywhere a record shows who last touched it (Job Tracker, Invoice
// Generator, Parts & Reference / Appliance Wiki, Dev Tools). Consolidated
// here on 2026-08-14 -- it used to be copy-pasted separately into all 4
// files, so the color map had to be updated in 4 places if it ever
// changed. Now there's just one. Only renders for a real, known account
// email; anything else gets no dot rather than a wrong guess. `label` is
// an optional verb prefix for the tooltip (e.g. "Last edited by",
// "Generated by") -- omit it for a bare-email tooltip.
const PERSON_DOT_COLORS = {
  'connor@triplehenterprisesllc.biz': '#7ec4ff',
  'steve@triplehenterprisesllc.biz': '#f0a8c8',
};
function personDot(email, label) {
  const color = PERSON_DOT_COLORS[(email || '').toLowerCase()];
  if (!color) return '';
  const safeEmail = typeof escapeHtml === 'function' ? escapeHtml(email) : email;
  const title = label ? (label + ' ' + safeEmail) : safeEmail;
  return '<span style="display:inline-block; width:7px; height:7px; border-radius:50%; background:' + color + '; margin-right:5px; vertical-align:middle;" title="' + title + '"></span>';
}

// Captured once, immediately -- before any button on the page could
// possibly have been clicked yet, since this script is deferred and only
// runs after the whole page has parsed. This means per-section "?"
// bubbles (openInfoModal) can safely reuse the exact same modal element
// as the page's main "How to Use" button, without ever permanently
// overwriting that page's real help content with whatever a bubble
// showed most recently.
let _fullHelpTitle = '';
let _fullHelpBody = '';
(function captureFullHelpContent() {
  const overlay = document.getElementById('helpModalOverlay');
  if (!overlay) return;
  const h3 = overlay.querySelector('h3');
  const body = overlay.querySelector('.help-modal-body');
  _fullHelpTitle = h3 ? h3.innerHTML : '';
  _fullHelpBody = body ? body.innerHTML : '';
})();

function openInfoModal(title, bodyHtml) {
  const overlay = document.getElementById('helpModalOverlay');
  if (!overlay) return;
  const h3 = overlay.querySelector('h3');
  const body = overlay.querySelector('.help-modal-body');
  if (h3) h3.innerHTML = title;
  if (body) body.innerHTML = bodyHtml;
  overlay.classList.add('is-open');
}

// Generic collapsed-icon search: a magnifying-glass button that expands
// into the real search input when tapped, and collapses back to just the
// icon if it loses focus while still empty -- keeps a page's toolbar
// compact until a search is actually wanted, everywhere this pattern is
// used across the app.
function toggleIconSearch(wrapId, forceOpen) {
  const wrap = document.getElementById(wrapId);
  if (!wrap) return;
  const input = wrap.querySelector('input');
  const shouldOpen = forceOpen !== undefined ? forceOpen : !wrap.classList.contains('is-expanded');
  if (shouldOpen) {
    wrap.classList.add('is-expanded');
    if (input) setTimeout(() => input.focus(), 50);
  } else {
    wrap.classList.remove('is-expanded');
  }
}
document.addEventListener('focusout', (e) => {
  const wrap = e.target.closest && e.target.closest('.icon-search');
  if (!wrap) return;
  setTimeout(() => {
    if (wrap.contains(document.activeElement)) return;
    const input = wrap.querySelector('input');
    if (input && !input.value.trim()) wrap.classList.remove('is-expanded');
  }, 120);
});

// Generic collapse/expand for "Add X"-style form sections -- used across
// multiple tool pages so a form starts collapsed and the page opens
// showing actual data first, rather than an empty form.
// Fades and collapses ONE specific row before its underlying data
// actually gets deleted and the list re-renders -- called from a real
// delete-button click, never from a render/filter pass, so this can
// never fire on every keystroke the way animating the whole list would.
// Measures the row's own real height first rather than guessing a fixed
// value, since these rows vary in height (wrapped text, extra fields).
function animateRowExit(rowElement, onComplete) {
  if (!rowElement) { onComplete(); return; }
  const reduceMotion = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reduceMotion) { onComplete(); return; }
  const isTableRow = rowElement.tagName === 'TR';
  // A <tr>'s rendered height is governed by the table layout algorithm,
  // not the normal box model -- max-height doesn't actually shrink a
  // table row's real height the way it does for a div, even though the
  // computed style itself transitions fine. Verified this directly
  // rather than assuming: for a <tr>, fall back to an opacity-only fade
  // instead of a collapse that would look subtly broken (correctly
  // fading, but leaving an empty gap where the row's height should be
  // shrinking) rather than actually smooth.
  if (isTableRow) {
    rowElement.style.transition = 'opacity .22s ease';
    requestAnimationFrame(() => { requestAnimationFrame(() => { rowElement.style.opacity = '0'; }); });
    setTimeout(onComplete, 230);
    return;
  }
  const height = rowElement.scrollHeight;
  rowElement.style.maxHeight = height + 'px';
  rowElement.style.overflow = 'hidden';
  rowElement.style.transition = 'opacity .22s ease, max-height .22s ease, margin .22s ease, padding .22s ease, border-width .22s ease';
  // Two rAFs, not one -- the browser needs to actually paint the
  // starting max-height (the row's real current height) as a distinct
  // frame before the target value changes, or the transition has
  // nothing to animate from and just snaps straight to the end state.
  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      rowElement.style.opacity = '0';
      rowElement.style.maxHeight = '0px';
      rowElement.style.marginTop = '0';
      rowElement.style.marginBottom = '0';
      rowElement.style.paddingTop = '0';
      rowElement.style.paddingBottom = '0';
      rowElement.style.borderWidth = '0';
    });
  });
  setTimeout(onComplete, 230);
}

// Swipe right anywhere on the page navigates back to Workspace, mirroring
// the native "swipe back" gesture already familiar from the rest of the
// phone. Content follows the finger in real time rather than only
// reacting after the gesture ends, and either completes the slide-away
// or springs back smoothly depending on whether the swipe actually
// cleared the threshold -- the same feel as a native back-swipe, not a
// binary "did this count or not" check with no feedback in between.
//
// Skips touches that start inside a <table> (a wide table on a narrow
// phone may need its own horizontal scroll), inside a <canvas> (signing
// a contract means dragging a finger across one, which can easily read
// as a horizontal swipe to this same detector -- without this exclusion,
// an in-progress signature gets silently aborted mid-stroke by a
// navigation neither the code nor the person intended), or while a modal
// is open. The modal case matters mechanically, not just visually:
// applying a transform to body creates a new containing block, which
// breaks position:fixed for every descendant -- an open modal would
// start moving with the page instead of staying fixed to the viewport.
function setupSwipeBackToWorkspace() {
  let touchStartX = 0, touchStartY = 0, touchStartTime = 0;
  let dragging = false, committed = false, visuallyDragged = false;
  const DRAG_ELEMENT = document.body;
  const THRESHOLD = 60;
  const MAX_DRAG = 140; // caps how far content visually follows the finger, even on a much longer drag

  function anyModalOpen() {
    return !!document.querySelector('.help-modal-overlay.is-open');
  }

  document.body.addEventListener('touchstart', (e) => {
    if (e.touches.length !== 1) return;
    touchStartX = e.touches[0].clientX;
    touchStartY = e.touches[0].clientY;
    touchStartTime = Date.now();
    dragging = !(e.target.closest && (e.target.closest('table') || e.target.closest('canvas'))) && !anyModalOpen();
    committed = false;
    visuallyDragged = false;
  }, { passive: true });

  document.body.addEventListener('touchmove', (e) => {
    if (!dragging || !e.touches.length) return;
    // A real signature is usually several separate strokes, lifted and
    // re-touched between letters -- checking only where a stroke started
    // isn't enough, since finger imprecision means any single stroke
    // could start a pixel outside the canvas's exact bounds and still be
    // part of the same signature. Checking continuously here means the
    // moment a drag crosses onto a canvas or table at all, swipe
    // detection cancels immediately, not just when it started there.
    if (e.target.closest && (e.target.closest('canvas') || e.target.closest('table'))) {
      dragging = false;
      DRAG_ELEMENT.style.transition = '';
      DRAG_ELEMENT.style.transform = '';
      DRAG_ELEMENT.style.opacity = '';
      return;
    }
    const dx = e.touches[0].clientX - touchStartX;
    const dy = e.touches[0].clientY - touchStartY;
    if (Math.abs(dx) < Math.abs(dy) * 1.5 || dx < 0) return; // not a rightward, mostly-horizontal drag -- leave scrolling alone
    const clamped = Math.min(dx, MAX_DRAG);
    visuallyDragged = true;
    DRAG_ELEMENT.style.transition = 'none';
    DRAG_ELEMENT.style.transform = `translateX(${clamped}px)`;
    DRAG_ELEMENT.style.opacity = String(1 - (clamped / MAX_DRAG) * 0.35);
  }, { passive: true });

  document.body.addEventListener('touchend', (e) => {
    if (!dragging || !visuallyDragged || !e.changedTouches.length) return;
    dragging = false;
    // Also check where the gesture ended, not just where it started or
    // passed through -- belt-and-suspenders with the touchmove check
    // above, since touchend's target can occasionally differ from the
    // last touchmove's target right at the boundary of an element.
    if (e.target.closest && (e.target.closest('canvas') || e.target.closest('table'))) {
      DRAG_ELEMENT.style.transition = '';
      DRAG_ELEMENT.style.transform = '';
      DRAG_ELEMENT.style.opacity = '';
      return;
    }
    const dx = e.changedTouches[0].clientX - touchStartX;
    const dy = e.changedTouches[0].clientY - touchStartY;
    const elapsed = Date.now() - touchStartTime;
    const isMostlyHorizontal = Math.abs(dx) > Math.abs(dy) * 1.5;
    const isFarEnough = dx > THRESHOLD;
    const isFastEnough = elapsed < 600;

    DRAG_ELEMENT.style.transition = 'transform .22s ease, opacity .22s ease';
    if (isMostlyHorizontal && isFarEnough && isFastEnough) {
      committed = true;
      DRAG_ELEMENT.style.transform = 'translateX(100%)';
      DRAG_ELEMENT.style.opacity = '0';
      setTimeout(() => { window.location.href = '/workspace.html'; }, 220);
    } else {
      DRAG_ELEMENT.style.transform = 'translateX(0)';
      DRAG_ELEMENT.style.opacity = '1';
      setTimeout(() => {
        if (!committed) { DRAG_ELEMENT.style.transition = ''; DRAG_ELEMENT.style.transform = ''; DRAG_ELEMENT.style.opacity = ''; }
      }, 230);
    }
  }, { passive: true });

  // A gesture can be interrupted (an incoming call, switching apps
  // mid-swipe) without ever firing touchend -- without this, content
  // could get stuck permanently dragged partway off-screen.
  document.body.addEventListener('touchcancel', () => {
    if (!dragging || !visuallyDragged) return;
    dragging = false;
    DRAG_ELEMENT.style.transition = 'transform .22s ease, opacity .22s ease';
    DRAG_ELEMENT.style.transform = 'translateX(0)';
    DRAG_ELEMENT.style.opacity = '1';
    setTimeout(() => { DRAG_ELEMENT.style.transition = ''; DRAG_ELEMENT.style.transform = ''; DRAG_ELEMENT.style.opacity = ''; }, 230);
  });
}

function toggleFormSection(id, forceOpen) {
  const el = document.getElementById(id);
  if (!el) return;
  if (forceOpen) el.classList.remove('is-collapsed');
  else el.classList.toggle('is-collapsed');
}

function openHelpModal() {
  openInfoModal(_fullHelpTitle, _fullHelpBody);
}

function closeHelpModal() {
  const overlay = document.getElementById('helpModalOverlay');
  if (overlay) overlay.classList.remove('is-open');
}

document.addEventListener('keydown', (e) => {
  if (e.key !== 'Escape') return;
  const dialogOverlay = document.getElementById('customDialogOverlay');
  if (dialogOverlay && dialogOverlay.classList.contains('is-open')) {
    const cancelBtn = document.getElementById('customDialogCancelAction');
    if (cancelBtn) cancelBtn.click();
    return;
  }
  closeHelpModal();
});

// ---------------------------------------------------------------------------
// Custom confirm/alert dialogs -- replace native browser confirm()/alert()
// with something styled to match the app instead of the browser's plain
// system dialog look. Both return a Promise, so call sites use `await`.
//
//   await showAlert('Something happened.');
//   const yes = await showConfirm('Delete this?', { danger: true });
//
// The overlay/panel are created once, lazily, and reused for every call.
// ---------------------------------------------------------------------------

function ensureDialogModalExists() {
  if (document.getElementById('customDialogOverlay')) return;
  const overlay = document.createElement('div');
  overlay.id = 'customDialogOverlay';
  overlay.className = 'help-modal-overlay';
  overlay.innerHTML =
    '<div class="help-modal">' +
      '<p class="dialog-message" id="customDialogMessage"></p>' +
      '<div class="dialog-buttons" id="customDialogButtons"></div>' +
    '</div>';
  document.body.appendChild(overlay);
  overlay.addEventListener('click', (e) => {
    // Clicking the dark backdrop (not the panel itself) cancels, same as
    // clicking outside the help modal already does elsewhere in the app.
    if (e.target === overlay) {
      const cancelBtn = document.getElementById('customDialogCancelAction');
      if (cancelBtn) cancelBtn.click();
    }
  });
}

function showAlert(message) {
  return new Promise((resolve) => {
    ensureDialogModalExists();
    const overlay = document.getElementById('customDialogOverlay');
    document.getElementById('customDialogMessage').textContent = message;
    const buttons = document.getElementById('customDialogButtons');
    buttons.innerHTML = '';

    const okBtn = document.createElement('button');
    okBtn.className = 'dialog-btn dialog-btn-primary';
    okBtn.id = 'customDialogCancelAction'; // Escape/backdrop-click resolves the same as OK for a plain alert
    okBtn.textContent = 'OK';
    okBtn.onclick = () => { overlay.classList.remove('is-open'); resolve(true); };
    buttons.appendChild(okBtn);

    overlay.classList.add('is-open');
    okBtn.focus();
  });
}

function showConfirm(message, options) {
  options = options || {};
  return new Promise((resolve) => {
    ensureDialogModalExists();
    const overlay = document.getElementById('customDialogOverlay');
    document.getElementById('customDialogMessage').textContent = message;
    const buttons = document.getElementById('customDialogButtons');
    buttons.innerHTML = '';

    const cancelBtn = document.createElement('button');
    cancelBtn.className = 'dialog-btn dialog-btn-cancel';
    cancelBtn.id = 'customDialogCancelAction'; // Escape/backdrop-click cancels, same as native confirm()
    cancelBtn.textContent = options.cancelText || 'Cancel';
    cancelBtn.onclick = () => { overlay.classList.remove('is-open'); resolve(false); };

    const confirmBtn = document.createElement('button');
    confirmBtn.className = 'dialog-btn ' + (options.danger ? 'dialog-btn-danger' : 'dialog-btn-primary');
    confirmBtn.textContent = options.confirmText || 'OK';
    confirmBtn.onclick = () => { overlay.classList.remove('is-open'); resolve(true); };

    buttons.appendChild(cancelBtn);
    buttons.appendChild(confirmBtn);
    overlay.classList.add('is-open');
  });
}

// ---------------------------------------------------------------------------
// Toast -- a brief, non-blocking confirmation for routine successes (job
// saved, invoice logged, contact deleted). Deliberately separate from
// showAlert()/showConfirm() above: those are for things that need an
// acknowledgment or a decision, this is for "that worked, keep going."
// Auto-dismisses; also dismissable early with a tap. Stacks if more than
// one fires in quick succession rather than replacing/losing the first.
//
//   showToast('Job added.');
//   showToast('Could not reach the server.', { type: 'error' });
// ---------------------------------------------------------------------------

function ensureToastContainerExists() {
  if (document.getElementById('thToastContainer')) return document.getElementById('thToastContainer');
  const container = document.createElement('div');
  container.id = 'thToastContainer';
  container.className = 'th-toast-container';
  container.setAttribute('aria-live', 'polite');
  container.setAttribute('role', 'status');
  document.body.appendChild(container);
  return container;
}

function showToast(message, options) {
  options = options || {};
  const duration = options.duration || 2600;
  const container = ensureToastContainerExists();

  const toast = document.createElement('div');
  toast.className = 'th-toast' + (options.type === 'error' ? ' is-error' : '');
  toast.textContent = message;
  toast.addEventListener('click', () => dismissToast(toast));
  container.appendChild(toast);

  // Letting the element paint in its resting state before adding
  // .is-shown means the CSS transition actually animates in, instead of
  // starting already-visible.
  requestAnimationFrame(() => toast.classList.add('is-shown'));

  const timer = setTimeout(() => dismissToast(toast), duration);
  toast._thTimer = timer;
}

function dismissToast(toast) {
  if (!toast || toast._thDismissed) return;
  toast._thDismissed = true;
  clearTimeout(toast._thTimer);
  toast.classList.remove('is-shown');
  setTimeout(() => toast.remove(), 200);
}

// ---------------------------------------------------------------------------
// Share-or-download for generated PDFs -- tries the native share sheet
// (text it, email it, AirDrop it) first on devices that support sharing
// files, falls back to a normal download everywhere else (most desktop
// browsers, or if the user cancels/it fails). The PDF still gets
// downloaded either way if sharing isn't available, so nothing is lost
// by trying the nicer path first.
// ---------------------------------------------------------------------------

function canShareFiles() {
  return !!(navigator.share && navigator.canShare);
}

async function sharePdfOrDownload(doc, filename, shareTitle) {
  if (canShareFiles()) {
    try {
      const blob = doc.output('blob');
      const file = new File([blob], filename, { type: 'application/pdf' });
      if (navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file], title: shareTitle || filename });
        return; // shared successfully -- no separate download needed
      }
    } catch (e) {
      // AbortError means the user just cancelled the share sheet --
      // respect that and don't fall back to forcing a download they
      // didn't ask for. Any OTHER error (share genuinely failed) falls
      // through to the normal download below instead.
      if (e.name === 'AbortError') return;
    }
  }
  doc.save(filename);
}

// PWA install support -- registers the service worker (see its own file
// for the network-first caching strategy, which gives real offline
// support without risking the stale-cache confusion this project has
// been bitten by before) and satisfies installability requirements in
// browsers that check for one before offering "Add to Home Screen".
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/service-worker.js').catch(() => {
      // Silently ignore -- the site works completely fine without the
      // service worker registering; this only affects the install prompt.
    });
  });
}

// Lightweight client-side error capture -- the cheap alternative to a
// paid error-tracking service for a project this size. Runs on every
// tool page (this file is shared by all of them), capped at the last
// 20 (per device before merging, and again after merging two devices'
// logs together -- see mergeClientErrorLog in sync.js) so it can't
// grow unbounded on a device that's been running a long time.
//
// Synced across devices (see sync.js) -- each entry gets its own
// unique id specifically so two devices' logs merge together safely
// instead of one overwriting the other. This was deliberately left
// device-local in an earlier version, right after the exact lesson
// about the synced payload's old 64 KiB size cap -- but that cap came
// from a `keepalive: true` flag on the push request that's since been
// removed entirely, so it no longer applies. Syncing this is what
// actually makes it useful for a two-person team: one person can now
// see what broke on the other's device, not just their own.
const CLIENT_ERROR_LOG_KEY = 'th_client_errors';
const CLIENT_ERROR_LOG_MAX = 20;

function logClientError(message, source, lineno, colno, stack) {
  try {
    let log = [];
    try { log = JSON.parse(localStorage.getItem(CLIENT_ERROR_LOG_KEY) || '[]'); } catch (e) { log = []; }
    log.unshift({
      // Random-suffixed id, not just Date.now() -- needed so two
      // different devices logging an error can merge correctly on
      // sync (see sync.js) without ever colliding, even in the
      // unlikely case both log something in the same millisecond.
      id: Date.now() + '-' + Math.random().toString(36).slice(2, 8),
      message: String(message == null ? 'Unknown error' : message).slice(0, 500),
      source: source || '',
      line: lineno || null,
      col: colno || null,
      stack: stack ? String(stack).slice(0, 1000) : '',
      page: (typeof window !== 'undefined' && window.location) ? window.location.pathname : '',
      time: new Date().toISOString(),
    });
    if (log.length > CLIENT_ERROR_LOG_MAX) log.length = CLIENT_ERROR_LOG_MAX;
    localStorage.setItem(CLIENT_ERROR_LOG_KEY, JSON.stringify(log));
    // sync.js loads after this file but before any real error could
    // actually fire, so scheduleSync will exist by the time this
    // callback runs for real -- same defensive guard used everywhere
    // else in this codebase that writes synced data.
    if (typeof scheduleSync === 'function') scheduleSync();
  } catch (e) {
    // If even logging the error fails, give up silently rather than
    // risk looping back into another error.
  }
}

window.addEventListener('error', (event) => {
  logClientError(event.message, event.filename, event.lineno, event.colno, event.error && event.error.stack);
});
window.addEventListener('unhandledrejection', (event) => {
  const reason = event.reason;
  logClientError(
    reason && reason.message ? reason.message : String(reason),
    '', null, null,
    reason && reason.stack
  );
});

// ---------------------------------------------------------------------------
// SWIPE-TO-DISMISS FOR MODALS -- added 2026-08-15
//
// Real drag physics rather than a "detect a flick, then close" shortcut:
// the modal actually tracks your finger, resists being pulled the wrong
// way, and either flies off or springs back based on how you release it.
//
// Three rules, all of which come from how native sheets behave:
//   1. VELOCITY OVERRIDES DISTANCE. A fast flick dismisses from anywhere,
//      even 20px in. A slow drag most of the way down still springs back
//      if you release it stationary -- because stopping means you changed
//      your mind. Judging on distance alone gets both cases wrong.
//   2. RESISTANCE UPWARD. Dragging up (the non-dismiss direction) moves
//      the modal a fraction of your finger's distance, on a curve, so it
//      feels tethered instead of broken.
//   3. NEVER FIGHT THE SCROLLBAR. .help-modal is `overflow-y:auto` and
//      can be taller than the screen. A drag only becomes a dismiss
//      gesture if the content is already scrolled to the very top AND
//      you're pulling downward. Otherwise it's a scroll and we don't
//      touch it. This is the single most common way swipe-to-dismiss
//      gets implemented badly.
// ---------------------------------------------------------------------------

const SWIPE_DISMISS_VELOCITY = 0.5;   // px/ms -- a genuine flick, matches the ~500px/s used by native sheet implementations
const SWIPE_DISMISS_DISTANCE = 0.25;  // fraction of modal height dragged past which a slow release still dismisses
const SWIPE_START_SLOP = 6;           // px of movement before committing to "this is a drag", so taps stay taps
const SWIPE_UP_RESISTANCE = 0.32;     // multiplier on upward (wrong-way) movement
const SWIPE_SPRING_BACK = 'transform .3s cubic-bezier(.22,1,.36,1)'; // decelerating ease-out, no overshoot wobble

function prefersReducedMotion() {
  return window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

function attachSwipeToDismiss(modalEl, onDismiss) {
  if (!modalEl || modalEl._swipeAttached) return;
  modalEl._swipeAttached = true;

  let startY = 0;
  let currentY = 0;
  let engaged = false;      // committed to dragging (vs scrolling or tapping)
  let decided = false;      // whether this touch has already been classified
  let lastY = 0;
  let lastT = 0;
  let velocity = 0;         // px/ms, positive = moving down

  function setOffset(px) {
    modalEl.style.transform = px ? 'translateY(' + px + 'px)' : '';
  }

  function reset(animate) {
    modalEl.style.transition = animate && !prefersReducedMotion() ? SWIPE_SPRING_BACK : '';
    setOffset(0);
    modalEl.style.opacity = '';
    if (animate) {
      setTimeout(() => { modalEl.style.transition = ''; }, 320);
    } else {
      modalEl.style.transition = '';
    }
  }

  modalEl.addEventListener('touchstart', (e) => {
    if (e.touches.length !== 1) return;
    startY = currentY = lastY = e.touches[0].clientY;
    lastT = e.timeStamp;
    velocity = 0;
    engaged = false;
    decided = false;
    modalEl.style.transition = '';
  }, { passive: true });

  // Not passive -- this handler needs preventDefault() to stop the page
  // scrolling underneath once a drag is actually engaged.
  modalEl.addEventListener('touchmove', (e) => {
    if (e.touches.length !== 1) return;
    const y = e.touches[0].clientY;
    const dy = y - startY;

    if (!decided) {
      if (Math.abs(dy) < SWIPE_START_SLOP) return; // still within tap slop
      decided = true;
      // Only a downward pull from an already-top-scrolled modal counts.
      // Anything else is the user scrolling the modal's own content.
      engaged = (dy > 0 && modalEl.scrollTop <= 0);
      if (!engaged) return;
    }
    if (!engaged) return;

    e.preventDefault();

    const dt = e.timeStamp - lastT;
    if (dt > 0) {
      // Smoothed so one jittery sample can't spike the reading
      velocity = 0.7 * ((y - lastY) / dt) + 0.3 * velocity;
      lastY = y;
      lastT = e.timeStamp;
    }
    currentY = y;

    const raw = y - startY;
    // Downward: follow the finger exactly. Upward: heavy resistance on a
    // curve, so it gives a little but clearly doesn't want to go there.
    const offset = raw >= 0 ? raw : -Math.pow(-raw, 0.8) * SWIPE_UP_RESISTANCE;
    setOffset(offset);
    // Fade slightly as it goes, so dismissal feels continuous rather than
    // a sudden disappearance at the end.
    if (offset > 0) {
      const fade = Math.max(0, 1 - (offset / (modalEl.offsetHeight || 400)) * 0.6);
      modalEl.style.opacity = String(fade);
    }
  }, { passive: false });

  modalEl.addEventListener('touchend', () => {
    if (!engaged) { decided = false; return; }
    engaged = false;
    decided = false;

    const travelled = currentY - startY;
    const height = modalEl.offsetHeight || 400;
    const flicked = velocity > SWIPE_DISMISS_VELOCITY;
    const draggedFar = travelled > height * SWIPE_DISMISS_DISTANCE;

    if (travelled > 0 && (flicked || draggedFar)) {
      if (prefersReducedMotion()) {
        reset(false);
        if (typeof onDismiss === 'function') onDismiss();
        return;
      }
      // Continue in the direction it was already moving rather than
      // snapping to a fixed animation -- keeps the motion continuous
      // with the finger that launched it.
      modalEl.style.transition = 'transform .22s ease-out, opacity .22s ease-out';
      setOffset(height);
      modalEl.style.opacity = '0';
      setTimeout(() => {
        reset(false);
        if (typeof onDismiss === 'function') onDismiss();
      }, 200);
    } else {
      reset(true);
    }
  }, { passive: true });

  modalEl.addEventListener('touchcancel', () => {
    if (engaged) reset(true);
    engaged = false;
    decided = false;
  }, { passive: true });
}

// Wires every .help-modal on the page to close its own overlay. Safe to
// call more than once -- _swipeAttached guards against double-binding.
function initSwipeToDismissModals() {
  document.querySelectorAll('.help-modal-overlay').forEach(overlay => {
    const modal = overlay.querySelector('.help-modal');
    if (!modal) return;
    attachSwipeToDismiss(modal, () => {
      overlay.classList.remove('is-open');
    });
  });
}

document.addEventListener('DOMContentLoaded', initSwipeToDismissModals);
