// Shared behavior for the internal Workspace tool suite.
// Loaded by workspace.html and every tool page via <script src="/tools-common.js" defer>.

// ---------------------------------------------------------------------------
// COMPLETION CELEBRATION -- added 2026-08-16. A brief, tasteful moment for
// completion events (marking a job done, crossing a revenue milestone) --
// small pieces falling from the top of the viewport for ~1.1s, then fully
// removed. Deliberately NOT used for routine actions (saving a form,
// syncing) -- reserved for things worth a small acknowledgment. Respects
// prefers-reduced-motion by skipping the falling pieces entirely and
// showing nothing rather than a static substitute -- a decorative moment
// isn't worth overriding someone's motion preference for.
// ---------------------------------------------------------------------------
function celebrateCompletion() {
  if (typeof document === 'undefined') return;
  if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  const colors = ['#ff8000', '#ffb347', '#d8d8d8', '#6fcf97'];
  const container = document.createElement('div');
  container.setAttribute('aria-hidden', 'true');
  container.style.cssText = 'position:fixed; inset:0; z-index:9999; pointer-events:none; overflow:hidden;';

  const pieceCount = 24;
  for (let i = 0; i < pieceCount; i++) {
    const piece = document.createElement('span');
    const size = 5 + Math.random() * 4;
    const left = Math.random() * 100;
    const delay = Math.random() * 0.15;
    const duration = 0.7 + Math.random() * 0.4;
    const drift = (Math.random() - 0.5) * 60;
    const color = colors[i % colors.length];
    piece.style.cssText =
      'position:absolute; top:-12px; left:' + left + 'vw; width:' + size + 'px; height:' + size + 'px;' +
      'background:' + color + '; border-radius:' + (i % 2 === 0 ? '50%' : '2px') + ';' +
      'opacity:0.9; transform:translateY(0);' +
      'animation:th-confetti-fall ' + duration + 's ease-in ' + delay + 's forwards;' +
      '--th-confetti-drift:' + drift + 'px;';
    container.appendChild(piece);
  }
  document.body.appendChild(container);
  setTimeout(() => container.remove(), 1300);
}

if (typeof document !== 'undefined' && !document.getElementById('thConfettiKeyframes')) {
  const style = document.createElement('style');
  style.id = 'thConfettiKeyframes';
  style.textContent = '@keyframes th-confetti-fall { to { transform: translate(var(--th-confetti-drift), 100vh) rotate(280deg); opacity: 0; } }';
  document.head.appendChild(style);
}

// Small color-coded attribution dot -- blue for Connor, pink for Steve.
// Used anywhere a record shows who last touched it (Job Tracker, Invoice
// Generator, Parts & Reference / Appliance Wiki, Dev Tools). Consolidated
// here on 2026-08-14 -- it used to be copy-pasted separately into all 4
// files, so the color map had to be updated in 4 places if it ever
// changed. Now there's just one. Only renders for a real, known account
// email; anything else gets no dot rather than a wrong guess. `label` is
// an optional verb prefix for the tooltip (e.g. "Last edited by",
// "Generated by") -- omit it for a bare-email tooltip.
const PERSON_DOT_COLORS = {
  'connor@triplehenterprisesllc.biz': '#7ec4ff',
  'steve@triplehenterprisesllc.biz': '#f0a8c8',
};
function personDot(email, label) {
  const color = PERSON_DOT_COLORS[(email || '').toLowerCase()];
  if (!color) return '';
  const safeEmail = typeof escapeHtml === 'function' ? escapeHtml(email) : email;
  const title = label ? (label + ' ' + safeEmail) : safeEmail;
  return '<span style="display:inline-block; width:7px; height:7px; border-radius:50%; background:' + color + '; margin-right:5px; vertical-align:middle;" title="' + title + '"></span>';
}

// Captured once, immediately -- before any button on the page could
// possibly have been clicked yet, since this script is deferred and only
// runs after the whole page has parsed. This means per-section "?"
// bubbles (openInfoModal) can safely reuse the exact same modal element
// as the page's main "How to Use" button, without ever permanently
// overwriting that page's real help content with whatever a bubble
// showed most recently.
let _fullHelpTitle = '';
let _fullHelpBody = '';
(function captureFullHelpContent() {
  const overlay = document.getElementById('helpModalOverlay');
  if (!overlay) return;
  const h3 = overlay.querySelector('h3');
  const body = overlay.querySelector('.help-modal-body');
  _fullHelpTitle = h3 ? h3.innerHTML : '';
  _fullHelpBody = body ? body.innerHTML : '';
})();

function openInfoModal(title, bodyHtml) {
  const overlay = document.getElementById('helpModalOverlay');
  if (!overlay) return;
  const h3 = overlay.querySelector('h3');
  const body = overlay.querySelector('.help-modal-body');
  if (h3) h3.innerHTML = title;
  if (body) body.innerHTML = bodyHtml;
  overlay.classList.add('is-open');
}

// Generic collapsed-icon search: a magnifying-glass button that expands
// into the real search input when tapped, and collapses back to just the
// icon if it loses focus while still empty -- keeps a page's toolbar
// compact until a search is actually wanted, everywhere this pattern is
// used across the app.
function toggleIconSearch(wrapId, forceOpen) {
  const wrap = document.getElementById(wrapId);
  if (!wrap) return;
  const input = wrap.querySelector('input');
  const shouldOpen = forceOpen !== undefined ? forceOpen : !wrap.classList.contains('is-expanded');
  if (shouldOpen) {
    wrap.classList.add('is-expanded');
    if (input) setTimeout(() => input.focus(), 50);
  } else {
    wrap.classList.remove('is-expanded');
  }
}
document.addEventListener('focusout', (e) => {
  const wrap = e.target.closest && e.target.closest('.icon-search');
  if (!wrap) return;
  setTimeout(() => {
    if (wrap.contains(document.activeElement)) return;
    const input = wrap.querySelector('input');
    if (input && !input.value.trim()) wrap.classList.remove('is-expanded');
  }, 120);
});

// Generic collapse/expand for "Add X"-style form sections -- used across
// multiple tool pages so a form starts collapsed and the page opens
// showing actual data first, rather than an empty form.
// Fades and collapses ONE specific row before its underlying data
// actually gets deleted and the list re-renders -- called from a real
// delete-button click, never from a render/filter pass, so this can
// never fire on every keystroke the way animating the whole list would.
// Measures the row's own real height first rather than guessing a fixed
// value, since these rows vary in height (wrapped text, extra fields).
function animateRowExit(rowElement, onComplete) {
  if (!rowElement) { onComplete(); return; }
  const reduceMotion = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reduceMotion) { onComplete(); return; }
  const isTableRow = rowElement.tagName === 'TR';
  // A <tr>'s rendered height is governed by the table layout algorithm,
  // not the normal box model -- max-height doesn't actually shrink a
  // table row's real height the way it does for a div, even though the
  // computed style itself transitions fine. Verified this directly
  // rather than assuming: for a <tr>, fall back to an opacity-only fade
  // instead of a collapse that would look subtly broken (correctly
  // fading, but leaving an empty gap where the row's height should be
  // shrinking) rather than actually smooth.
  if (isTableRow) {
    rowElement.style.transition = 'opacity .22s ease';
    requestAnimationFrame(() => { requestAnimationFrame(() => { rowElement.style.opacity = '0'; }); });
    setTimeout(onComplete, 230);
    return;
  }
  const height = rowElement.scrollHeight;
  rowElement.style.maxHeight = height + 'px';
  rowElement.style.overflow = 'hidden';
  rowElement.style.transition = 'opacity .22s ease, max-height .22s ease, margin .22s ease, padding .22s ease, border-width .22s ease';
  // Two rAFs, not one -- the browser needs to actually paint the
  // starting max-height (the row's real current height) as a distinct
  // frame before the target value changes, or the transition has
  // nothing to animate from and just snaps straight to the end state.
  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      rowElement.style.opacity = '0';
      rowElement.style.maxHeight = '0px';
      rowElement.style.marginTop = '0';
      rowElement.style.marginBottom = '0';
      rowElement.style.paddingTop = '0';
      rowElement.style.paddingBottom = '0';
      rowElement.style.borderWidth = '0';
    });
  });
  setTimeout(onComplete, 230);
}

// Swipe right anywhere on the page navigates back to Workspace, mirroring
// the native "swipe back" gesture already familiar from the rest of the
// phone. Content follows the finger in real time rather than only
// reacting after the gesture ends, and either completes the slide-away
// or springs back smoothly depending on whether the swipe actually
// cleared the threshold -- the same feel as a native back-swipe, not a
// binary "did this count or not" check with no feedback in between.
//
// Skips touches that start inside a <table> (a wide table on a narrow
// phone may need its own horizontal scroll), inside a <canvas> (signing
// a contract means dragging a finger across one, which can easily read
// as a horizontal swipe to this same detector -- without this exclusion,
// an in-progress signature gets silently aborted mid-stroke by a
// navigation neither the code nor the person intended), or while a modal
// is open. The modal case matters mechanically, not just visually:
// applying a transform to body creates a new containing block, which
// breaks position:fixed for every descendant -- an open modal would
// start moving with the page instead of staying fixed to the viewport.
function setupSwipeBackToWorkspace() {
  let touchStartX = 0, touchStartY = 0, touchStartTime = 0;
  let dragging = false, committed = false, visuallyDragged = false;
  const DRAG_ELEMENT = document.body;
  const THRESHOLD = 60;
  const MAX_DRAG = 140; // caps how far content visually follows the finger, even on a much longer drag

  function anyModalOpen() {
    return !!document.querySelector('.help-modal-overlay.is-open');
  }

  document.body.addEventListener('touchstart', (e) => {
    if (e.touches.length !== 1) return;
    touchStartX = e.touches[0].clientX;
    touchStartY = e.touches[0].clientY;
    touchStartTime = Date.now();
    dragging = !(e.target.closest && (e.target.closest('table') || e.target.closest('canvas'))) && !anyModalOpen();
    committed = false;
    visuallyDragged = false;
  }, { passive: true });

  document.body.addEventListener('touchmove', (e) => {
    if (!dragging || !e.touches.length) return;
    // A real signature is usually several separate strokes, lifted and
    // re-touched between letters -- checking only where a stroke started
    // isn't enough, since finger imprecision means any single stroke
    // could start a pixel outside the canvas's exact bounds and still be
    // part of the same signature. Checking continuously here means the
    // moment a drag crosses onto a canvas or table at all, swipe
    // detection cancels immediately, not just when it started there.
    if (e.target.closest && (e.target.closest('canvas') || e.target.closest('table'))) {
      dragging = false;
      DRAG_ELEMENT.style.transition = '';
      DRAG_ELEMENT.style.transform = '';
      DRAG_ELEMENT.style.opacity = '';
      return;
    }
    const dx = e.touches[0].clientX - touchStartX;
    const dy = e.touches[0].clientY - touchStartY;
    if (Math.abs(dx) < Math.abs(dy) * 1.5 || dx < 0) return; // not a rightward, mostly-horizontal drag -- leave scrolling alone
    const clamped = Math.min(dx, MAX_DRAG);
    visuallyDragged = true;
    DRAG_ELEMENT.style.transition = 'none';
    DRAG_ELEMENT.style.transform = `translateX(${clamped}px)`;
    DRAG_ELEMENT.style.opacity = String(1 - (clamped / MAX_DRAG) * 0.35);
  }, { passive: true });

  document.body.addEventListener('touchend', (e) => {
    if (!dragging || !visuallyDragged || !e.changedTouches.length) return;
    dragging = false;
    // Also check where the gesture ended, not just where it started or
    // passed through -- belt-and-suspenders with the touchmove check
    // above, since touchend's target can occasionally differ from the
    // last touchmove's target right at the boundary of an element.
    if (e.target.closest && (e.target.closest('canvas') || e.target.closest('table'))) {
      DRAG_ELEMENT.style.transition = '';
      DRAG_ELEMENT.style.transform = '';
      DRAG_ELEMENT.style.opacity = '';
      return;
    }
    const dx = e.changedTouches[0].clientX - touchStartX;
    const dy = e.changedTouches[0].clientY - touchStartY;
    const elapsed = Date.now() - touchStartTime;
    const isMostlyHorizontal = Math.abs(dx) > Math.abs(dy) * 1.5;
    const isFarEnough = dx > THRESHOLD;
    const isFastEnough = elapsed < 600;

    DRAG_ELEMENT.style.transition = 'transform .22s ease, opacity .22s ease';
    if (isMostlyHorizontal && isFarEnough && isFastEnough) {
      committed = true;
      DRAG_ELEMENT.style.transform = 'translateX(100%)';
      DRAG_ELEMENT.style.opacity = '0';
      setTimeout(() => { window.location.href = '/workspace.html'; }, 220);
    } else {
      DRAG_ELEMENT.style.transform = 'translateX(0)';
      DRAG_ELEMENT.style.opacity = '1';
      setTimeout(() => {
        if (!committed) { DRAG_ELEMENT.style.transition = ''; DRAG_ELEMENT.style.transform = ''; DRAG_ELEMENT.style.opacity = ''; }
      }, 230);
    }
  }, { passive: true });

  // A gesture can be interrupted (an incoming call, switching apps
  // mid-swipe) without ever firing touchend -- without this, content
  // could get stuck permanently dragged partway off-screen.
  document.body.addEventListener('touchcancel', () => {
    if (!dragging || !visuallyDragged) return;
    dragging = false;
    DRAG_ELEMENT.style.transition = 'transform .22s ease, opacity .22s ease';
    DRAG_ELEMENT.style.transform = 'translateX(0)';
    DRAG_ELEMENT.style.opacity = '1';
    setTimeout(() => { DRAG_ELEMENT.style.transition = ''; DRAG_ELEMENT.style.transform = ''; DRAG_ELEMENT.style.opacity = ''; }, 230);
  });
}

function toggleFormSection(id, forceOpen) {
  const el = document.getElementById(id);
  if (!el) return;
  if (forceOpen) el.classList.remove('is-collapsed');
  else el.classList.toggle('is-collapsed');
}

function openHelpModal() {
  openInfoModal(_fullHelpTitle, _fullHelpBody);
}

function closeHelpModal() {
  const overlay = document.getElementById('helpModalOverlay');
  if (overlay) overlay.classList.remove('is-open');
}

document.addEventListener('keydown', (e) => {
  if (e.key !== 'Escape') return;
  const dialogOverlay = document.getElementById('customDialogOverlay');
  if (dialogOverlay && dialogOverlay.classList.contains('is-open')) {
    const cancelBtn = document.getElementById('customDialogCancelAction');
    if (cancelBtn) cancelBtn.click();
    return;
  }
  closeHelpModal();
});

// ---------------------------------------------------------------------------
// Custom confirm/alert dialogs -- replace native browser confirm()/alert()
// with something styled to match the app instead of the browser's plain
// system dialog look. Both return a Promise, so call sites use `await`.
//
//   await showAlert('Something happened.');
//   const yes = await showConfirm('Delete this?', { danger: true });
//
// The overlay/panel are created once, lazily, and reused for every call.
// ---------------------------------------------------------------------------

function ensureDialogModalExists() {
  if (document.getElementById('customDialogOverlay')) return;
  const overlay = document.createElement('div');
  overlay.id = 'customDialogOverlay';
  overlay.className = 'help-modal-overlay';
  overlay.innerHTML =
    '<div class="help-modal">' +
      '<p class="dialog-message" id="customDialogMessage"></p>' +
      '<div class="dialog-buttons" id="customDialogButtons"></div>' +
    '</div>';
  document.body.appendChild(overlay);
  overlay.addEventListener('click', (e) => {
    // Clicking the dark backdrop (not the panel itself) cancels, same as
    // clicking outside the help modal already does elsewhere in the app.
    if (e.target === overlay) {
      const cancelBtn = document.getElementById('customDialogCancelAction');
      if (cancelBtn) cancelBtn.click();
    }
  });
}

function showAlert(message) {
  return new Promise((resolve) => {
    ensureDialogModalExists();
    const overlay = document.getElementById('customDialogOverlay');
    document.getElementById('customDialogMessage').textContent = message;
    const buttons = document.getElementById('customDialogButtons');
    buttons.innerHTML = '';

    const okBtn = document.createElement('button');
    okBtn.className = 'dialog-btn dialog-btn-primary';
    okBtn.id = 'customDialogCancelAction'; // Escape/backdrop-click resolves the same as OK for a plain alert
    okBtn.textContent = 'OK';
    okBtn.onclick = () => { overlay.classList.remove('is-open'); resolve(true); };
    buttons.appendChild(okBtn);

    overlay.classList.add('is-open');
    okBtn.focus();
  });
}

function showConfirm(message, options) {
  options = options || {};
  return new Promise((resolve) => {
    ensureDialogModalExists();
    const overlay = document.getElementById('customDialogOverlay');
    document.getElementById('customDialogMessage').textContent = message;
    const buttons = document.getElementById('customDialogButtons');
    buttons.innerHTML = '';

    const cancelBtn = document.createElement('button');
    cancelBtn.className = 'dialog-btn dialog-btn-cancel';
    cancelBtn.id = 'customDialogCancelAction'; // Escape/backdrop-click cancels, same as native confirm()
    cancelBtn.textContent = options.cancelText || 'Cancel';
    cancelBtn.onclick = () => { overlay.classList.remove('is-open'); resolve(false); };

    const confirmBtn = document.createElement('button');
    confirmBtn.className = 'dialog-btn ' + (options.danger ? 'dialog-btn-danger' : 'dialog-btn-primary');
    confirmBtn.textContent = options.confirmText || 'OK';
    confirmBtn.onclick = () => { overlay.classList.remove('is-open'); resolve(true); };

    buttons.appendChild(cancelBtn);
    buttons.appendChild(confirmBtn);
    overlay.classList.add('is-open');
  });
}

// ---------------------------------------------------------------------------
// Toast -- a brief, non-blocking confirmation for routine successes (job
// saved, invoice logged, contact deleted). Deliberately separate from
// showAlert()/showConfirm() above: those are for things that need an
// acknowledgment or a decision, this is for "that worked, keep going."
// Auto-dismisses; also dismissable early with a tap. Stacks if more than
// one fires in quick succession rather than replacing/losing the first.
//
//   showToast('Job added.');
//   showToast('Could not reach the server.', { type: 'error' });
// ---------------------------------------------------------------------------

function ensureToastContainerExists() {
  if (document.getElementById('thToastContainer')) return document.getElementById('thToastContainer');
  const container = document.createElement('div');
  container.id = 'thToastContainer';
  container.className = 'th-toast-container';
  container.setAttribute('aria-live', 'polite');
  container.setAttribute('role', 'status');
  document.body.appendChild(container);
  return container;
}

// ---------------------------------------------------------------------------
// LONG-PRESS via event delegation -- added 2026-08-17 (item #9). Chosen
// over a swipe-action system: a hold-timer has no distance/velocity math
// to get wrong and can never be misread as a scroll gesture the way a
// horizontal swipe can, since it's cancelled the moment the pointer
// moves more than a few pixels. Uses pointer events (not touch-specific)
// so it works identically with touch and mouse, no separate desktop
// fallback needed.
//
// Delegated on a container rather than attached per-item, so a list that
// re-renders on every data change (job cards, etc.) never risks
// re-attaching duplicate listeners -- this is wired once per container,
// ever.
function attachLongPress(containerEl, itemSelector, onLongPress) {
  const HOLD_MS = 500;
  const MOVE_CANCEL_PX = 10;
  let timer = null;
  let startX = 0, startY = 0, activeEl = null;

  function cancel() {
    clearTimeout(timer);
    timer = null;
    if (activeEl) activeEl.classList.remove('is-long-pressing');
    activeEl = null;
  }

  containerEl.addEventListener('pointerdown', (e) => {
    const item = e.target.closest(itemSelector);
    if (!item || !containerEl.contains(item)) return;
    // A long-press on an interactive control inside the card (a button,
    // select, or link) should never hijack that control's own normal
    // tap behavior.
    if (e.target.closest('button, a, select, input, textarea')) return;

    activeEl = item;
    startX = e.clientX;
    startY = e.clientY;
    timer = setTimeout(() => {
      if (!activeEl) return;
      activeEl.classList.remove('is-long-pressing');
      if (navigator.vibrate) navigator.vibrate(12); // no-ops silently where unsupported (notably iOS Safari)
      const el = activeEl;
      activeEl = null;
      onLongPress(el);
    }, HOLD_MS);
    item.classList.add('is-long-pressing');
  }, { passive: true });

  containerEl.addEventListener('pointermove', (e) => {
    if (!activeEl) return;
    if (Math.abs(e.clientX - startX) > MOVE_CANCEL_PX || Math.abs(e.clientY - startY) > MOVE_CANCEL_PX) cancel();
  }, { passive: true });

  containerEl.addEventListener('pointerup', cancel, { passive: true });
  containerEl.addEventListener('pointercancel', cancel, { passive: true });
  containerEl.addEventListener('scroll', cancel, { passive: true });
}

// Small bottom-sheet action menu, triggered by attachLongPress above.
// actions: [{ label, onClick, isDanger }]
function showQuickActionSheet(title, actions) {
  const overlay = document.createElement('div');
  overlay.className = 'quick-actions-overlay';
  const sheet = document.createElement('div');
  sheet.className = 'quick-actions-sheet';
  sheet.innerHTML =
    '<div class="quick-actions-title">' + title + '</div>' +
    actions.map((a, i) =>
      '<button class="quick-actions-btn' + (a.isDanger ? ' is-danger' : '') + '" data-action-index="' + i + '">' + a.label + '</button>'
    ).join('') +
    '<button class="quick-actions-btn quick-actions-cancel">Cancel</button>';

  function close() {
    overlay.classList.remove('is-shown');
    setTimeout(() => overlay.remove(), 200);
  }
  overlay.addEventListener('click', (e) => { if (e.target === overlay) close(); });
  sheet.querySelector('.quick-actions-cancel').addEventListener('click', close);
  actions.forEach((a, i) => {
    sheet.querySelector('[data-action-index="' + i + '"]').addEventListener('click', () => {
      close();
      a.onClick();
    });
  });

  overlay.appendChild(sheet);
  document.body.appendChild(overlay);
  requestAnimationFrame(() => overlay.classList.add('is-shown'));
}

function showToast(message, options) {
  options = options || {};
  const duration = options.duration || 2600;
  const container = ensureToastContainerExists();

  const toast = document.createElement('div');
  toast.className = 'th-toast' + (options.type === 'error' ? ' is-error' : '');
  const iconName = options.type === 'error' ? 'warning' : 'check-circle';
  toast.innerHTML =
    '<svg class="th-icon" aria-hidden="true"><use href="#icon-' + iconName + '" xlink:href="#icon-' + iconName + '"></use></svg>' +
    '<span></span>';
  toast.querySelector('span').textContent = message; // textContent, not innerHTML -- message may contain user data
  toast.addEventListener('click', () => dismissToast(toast));
  container.appendChild(toast);

  // Letting the element paint in its resting state before adding
  // .is-shown means the CSS transition actually animates in, instead of
  // starting already-visible.
  requestAnimationFrame(() => toast.classList.add('is-shown'));

  const timer = setTimeout(() => dismissToast(toast), duration);
  toast._thTimer = timer;
}

function dismissToast(toast) {
  if (!toast || toast._thDismissed) return;
  toast._thDismissed = true;
  clearTimeout(toast._thTimer);
  toast.classList.remove('is-shown');
  setTimeout(() => toast.remove(), 200);
}

// ---------------------------------------------------------------------------
// Share-or-download for generated PDFs -- tries the native share sheet
// (text it, email it, AirDrop it) first on devices that support sharing
// files, falls back to a normal download everywhere else (most desktop
// browsers, or if the user cancels/it fails). The PDF still gets
// downloaded either way if sharing isn't available, so nothing is lost
// by trying the nicer path first.
// ---------------------------------------------------------------------------

function canShareFiles() {
  return !!(navigator.share && navigator.canShare);
}

async function sharePdfOrDownload(doc, filename, shareTitle) {
  if (canShareFiles()) {
    try {
      const blob = doc.output('blob');
      const file = new File([blob], filename, { type: 'application/pdf' });
      if (navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file], title: shareTitle || filename });
        return; // shared successfully -- no separate download needed
      }
    } catch (e) {
      // AbortError means the user just cancelled the share sheet --
      // respect that and don't fall back to forcing a download they
      // didn't ask for. Any OTHER error (share genuinely failed) falls
      // through to the normal download below instead.
      if (e.name === 'AbortError') return;
    }
  }
  doc.save(filename);
}

// PWA install support -- registers the service worker (see its own file
// for the network-first caching strategy, which gives real offline
// support without risking the stale-cache confusion this project has
// been bitten by before) and satisfies installability requirements in
// browsers that check for one before offering "Add to Home Screen".
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/service-worker.js').catch(() => {
      // Silently ignore -- the site works completely fine without the
      // service worker registering; this only affects the install prompt.
    });
  });
}

// Lightweight client-side error capture -- the cheap alternative to a
// paid error-tracking service for a project this size. Runs on every
// tool page (this file is shared by all of them), capped at the last
// 20 (per device before merging, and again after merging two devices'
// logs together -- see mergeClientErrorLog in sync.js) so it can't
// grow unbounded on a device that's been running a long time.
//
// Synced across devices (see sync.js) -- each entry gets its own
// unique id specifically so two devices' logs merge together safely
// instead of one overwriting the other. This was deliberately left
// device-local in an earlier version, right after the exact lesson
// about the synced payload's old 64 KiB size cap -- but that cap came
// from a `keepalive: true` flag on the push request that's since been
// removed entirely, so it no longer applies. Syncing this is what
// actually makes it useful for a two-person team: one person can now
// see what broke on the other's device, not just their own.
const CLIENT_ERROR_LOG_KEY = 'th_client_errors';
const CLIENT_ERROR_LOG_MAX = 20;

function logClientError(message, source, lineno, colno, stack) {
  try {
    let log = [];
    try { log = JSON.parse(localStorage.getItem(CLIENT_ERROR_LOG_KEY) || '[]'); } catch (e) { log = []; }
    log.unshift({
      // Random-suffixed id, not just Date.now() -- needed so two
      // different devices logging an error can merge correctly on
      // sync (see sync.js) without ever colliding, even in the
      // unlikely case both log something in the same millisecond.
      id: Date.now() + '-' + Math.random().toString(36).slice(2, 8),
      message: String(message == null ? 'Unknown error' : message).slice(0, 500),
      source: source || '',
      line: lineno || null,
      col: colno || null,
      stack: stack ? String(stack).slice(0, 1000) : '',
      page: (typeof window !== 'undefined' && window.location) ? window.location.pathname : '',
      time: new Date().toISOString(),
    });
    if (log.length > CLIENT_ERROR_LOG_MAX) log.length = CLIENT_ERROR_LOG_MAX;
    localStorage.setItem(CLIENT_ERROR_LOG_KEY, JSON.stringify(log));
    // sync.js loads after this file but before any real error could
    // actually fire, so scheduleSync will exist by the time this
    // callback runs for real -- same defensive guard used everywhere
    // else in this codebase that writes synced data.
    if (typeof scheduleSync === 'function') scheduleSync();
  } catch (e) {
    // If even logging the error fails, give up silently rather than
    // risk looping back into another error.
  }
}

window.addEventListener('error', (event) => {
  logClientError(event.message, event.filename, event.lineno, event.colno, event.error && event.error.stack);
});
window.addEventListener('unhandledrejection', (event) => {
  const reason = event.reason;
  logClientError(
    reason && reason.message ? reason.message : String(reason),
    '', null, null,
    reason && reason.stack
  );
});

// ---------------------------------------------------------------------------
// SWIPE-TO-DISMISS FOR MODALS -- added 2026-08-15
//
// Real drag physics rather than a "detect a flick, then close" shortcut:
// the modal actually tracks your finger, resists being pulled the wrong
// way, and either flies off or springs back based on how you release it.
//
// Three rules, all of which come from how native sheets behave:
//   1. VELOCITY OVERRIDES DISTANCE. A fast flick dismisses from anywhere,
//      even 20px in. A slow drag most of the way down still springs back
//      if you release it stationary -- because stopping means you changed
//      your mind. Judging on distance alone gets both cases wrong.
//   2. RESISTANCE UPWARD. Dragging up (the non-dismiss direction) moves
//      the modal a fraction of your finger's distance, on a curve, so it
//      feels tethered instead of broken.
//   3. NEVER FIGHT THE SCROLLBAR. .help-modal is `overflow-y:auto` and
//      can be taller than the screen. A drag only becomes a dismiss
//      gesture if the content is already scrolled to the very top AND
//      you're pulling downward. Otherwise it's a scroll and we don't
//      touch it. This is the single most common way swipe-to-dismiss
//      gets implemented badly.
// ---------------------------------------------------------------------------

const SWIPE_DISMISS_VELOCITY = 0.5;   // px/ms -- a genuine flick, matches the ~500px/s used by native sheet implementations
const SWIPE_DISMISS_DISTANCE = 0.25;  // fraction of modal height dragged past which a slow release still dismisses
const SWIPE_START_SLOP = 6;           // px of movement before committing to "this is a drag", so taps stay taps
const SWIPE_UP_RESISTANCE = 0.32;     // multiplier on upward (wrong-way) movement
const SWIPE_SPRING_BACK = 'transform .3s cubic-bezier(.22,1,.36,1)'; // decelerating ease-out, no overshoot wobble

function prefersReducedMotion() {
  return window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

function attachSwipeToDismiss(modalEl, onDismiss) {
  if (!modalEl || modalEl._swipeAttached) return;
  modalEl._swipeAttached = true;

  let startY = 0;
  let currentY = 0;
  let engaged = false;      // committed to dragging (vs scrolling or tapping)
  let decided = false;      // whether this touch has already been classified
  let lastY = 0;
  let lastT = 0;
  let velocity = 0;         // px/ms, positive = moving down

  function setOffset(px) {
    modalEl.style.transform = px ? 'translateY(' + px + 'px)' : '';
  }

  function reset(animate) {
    modalEl.style.transition = animate && !prefersReducedMotion() ? SWIPE_SPRING_BACK : '';
    setOffset(0);
    modalEl.style.opacity = '';
    if (animate) {
      setTimeout(() => { modalEl.style.transition = ''; }, 320);
    } else {
      modalEl.style.transition = '';
    }
  }

  modalEl.addEventListener('touchstart', (e) => {
    if (e.touches.length !== 1) return;
    startY = currentY = lastY = e.touches[0].clientY;
    lastT = e.timeStamp;
    velocity = 0;
    engaged = false;
    decided = false;
    modalEl.style.transition = '';
  }, { passive: true });

  // Not passive -- this handler needs preventDefault() to stop the page
  // scrolling underneath once a drag is actually engaged.
  modalEl.addEventListener('touchmove', (e) => {
    if (e.touches.length !== 1) return;
    const y = e.touches[0].clientY;
    const dy = y - startY;

    if (!decided) {
      if (Math.abs(dy) < SWIPE_START_SLOP) return; // still within tap slop
      decided = true;
      // Only a downward pull from an already-top-scrolled modal counts.
      // Anything else is the user scrolling the modal's own content.
      engaged = (dy > 0 && modalEl.scrollTop <= 0);
      if (!engaged) return;
    }
    if (!engaged) return;

    e.preventDefault();

    const dt = e.timeStamp - lastT;
    if (dt > 0) {
      // Smoothed so one jittery sample can't spike the reading
      velocity = 0.7 * ((y - lastY) / dt) + 0.3 * velocity;
      lastY = y;
      lastT = e.timeStamp;
    }
    currentY = y;

    const raw = y - startY;
    // Downward: follow the finger exactly. Upward: heavy resistance on a
    // curve, so it gives a little but clearly doesn't want to go there.
    const offset = raw >= 0 ? raw : -Math.pow(-raw, 0.8) * SWIPE_UP_RESISTANCE;
    setOffset(offset);
    // Fade slightly as it goes, so dismissal feels continuous rather than
    // a sudden disappearance at the end.
    if (offset > 0) {
      const fade = Math.max(0, 1 - (offset / (modalEl.offsetHeight || 400)) * 0.6);
      modalEl.style.opacity = String(fade);
    }
  }, { passive: false });

  modalEl.addEventListener('touchend', () => {
    if (!engaged) { decided = false; return; }
    engaged = false;
    decided = false;

    const travelled = currentY - startY;
    const height = modalEl.offsetHeight || 400;
    const flicked = velocity > SWIPE_DISMISS_VELOCITY;
    const draggedFar = travelled > height * SWIPE_DISMISS_DISTANCE;

    if (travelled > 0 && (flicked || draggedFar)) {
      if (prefersReducedMotion()) {
        reset(false);
        if (typeof onDismiss === 'function') onDismiss();
        return;
      }
      // Continue in the direction it was already moving rather than
      // snapping to a fixed animation -- keeps the motion continuous
      // with the finger that launched it.
      modalEl.style.transition = 'transform .22s ease-out, opacity .22s ease-out';
      setOffset(height);
      modalEl.style.opacity = '0';
      setTimeout(() => {
        reset(false);
        if (typeof onDismiss === 'function') onDismiss();
      }, 200);
    } else {
      reset(true);
    }
  }, { passive: true });

  modalEl.addEventListener('touchcancel', () => {
    if (engaged) reset(true);
    engaged = false;
    decided = false;
  }, { passive: true });
}

// Wires every .help-modal on the page to close its own overlay. Safe to
// call more than once -- _swipeAttached guards against double-binding.
function initSwipeToDismissModals() {
  document.querySelectorAll('.help-modal-overlay').forEach(overlay => {
    const modal = overlay.querySelector('.help-modal');
    if (!modal) return;
    attachSwipeToDismiss(modal, () => {
      overlay.classList.remove('is-open');
    });
  });
}

document.addEventListener('DOMContentLoaded', initSwipeToDismissModals);

// ---------------------------------------------------------------------------
// MOBILE BOTTOM APP NAV -- added 2026-08-16 (redesign v2)
// Injected here so every tool page gets it from one file. Styled entirely
// by the "TOOL SUITE REDESIGN v2" layer in /styles.css (.th-bottom-nav),
// which only displays it under 720px -- desktop never sees it. Also tags
// <body> with th-tool-page (ambient background + radius tokens) and
// th-has-bottomnav (bottom padding so content clears the fixed bar).
// login.html is excluded: no point navigating before you're signed in.
// ---------------------------------------------------------------------------
(function () {
  if (typeof document === 'undefined') return;
  var path = (window.location && window.location.pathname) || '';
  var onLogin = /\/login\.html$/.test(path);

  var DESTS = [
    { href: '/tools/workspace.html',         icon: 'home',    label: 'Home' },
    { href: '/tools/job-tracker.html',       icon: 'wrench',  label: 'Jobs' },
    { href: '/tools/invoice-generator.html', icon: 'receipt', label: 'Invoices' },
    { href: '/tools/calendar.html',          icon: 'calendar',label: 'Calendar' },
    { href: '/tools/route-planner.html',     icon: 'map',     label: 'Routes' }
  ];

  function inject() {
    document.body.classList.add('th-tool-page');
    if (onLogin) return;
    document.body.classList.add('th-has-bottomnav');

    var nav = document.createElement('nav');
    nav.className = 'th-bottom-nav';
    nav.setAttribute('aria-label', 'Quick navigation');
    nav.innerHTML = DESTS.map(function (d) {
      var active = path === d.href ? ' is-active' : '';
      var current = path === d.href ? ' aria-current="page"' : '';
      return '<a href="' + d.href + '" class="' + active.trim() + '"' + current + '>' +
        '<span class="th-bn-icon" aria-hidden="true"><svg class="th-icon" aria-hidden="true"><use href="#icon-' + d.icon + '" xlink:href="#icon-' + d.icon + '"></use></svg></span>' +
        '<span>' + d.label + '</span></a>';
    }).join('');
    document.body.appendChild(nav);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', inject);
  } else {
    inject();
  }
})();

// ---------------------------------------------------------------------------
// DISPLAY DENSITY TOGGLE -- added 2026-08-16. A personal display
// preference (comfortable vs compact row spacing), so it lives in plain
// localStorage rather than the synced data blob -- there's no reason a
// density choice made on one device should override another's screen
// size preference. Applies as a body class; each page's own CSS defines
// what ".is-compact-density" actually tightens for its own row markup.
// ---------------------------------------------------------------------------
const DENSITY_KEY = 'th_density';

function loadDensityPreference() {
  try { return localStorage.getItem(DENSITY_KEY) === 'compact' ? 'compact' : 'comfortable'; }
  catch (e) { return 'comfortable'; }
}

function applyDensityPreference() {
  const density = loadDensityPreference();
  document.body.classList.toggle('is-compact-density', density === 'compact');
  document.querySelectorAll('[data-density-toggle]').forEach(btn => {
    btn.setAttribute('aria-pressed', density === 'compact' ? 'true' : 'false');
    btn.textContent = density === 'compact' ? 'Comfortable view' : 'Compact view';
  });
}

function toggleDensityPreference() {
  const next = loadDensityPreference() === 'compact' ? 'comfortable' : 'compact';
  try { localStorage.setItem(DENSITY_KEY, next); } catch (e) { /* ignore */ }
  applyDensityPreference();
}

if (typeof document !== 'undefined') {
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', applyDensityPreference);
  } else {
    applyDensityPreference();
  }
}
// ---------------------------------------------------------------------------
// SHARED ICON SPRITE -- added 2026-08-16 (visual redesign v3)
// Replaces the 29 semantic pictographic emoji used across the tool suite
// (search/trash/camera/wrench/bell/etc.) with one original, consistent
// stroke-based SVG set. Emoji render completely differently per OS --
// Windows renders them flatter and more literal than iOS/Android -- so
// the same icon looked like two different apps depending on the device.
// This sprite is injected once into every page (from this shared file)
// as a hidden <svg><defs><symbol>...</symbol></defs></svg> block; every
// page then references icons with <svg class="th-icon"><use href="#icon-
// name"/></svg>, sized and colored entirely by CSS (.th-icon in
// styles.css), so every icon automatically matches the current theme
// and inherits its container's text color.
//
// Left alone on purpose: plain typographic marks (chevrons, checkmarks,
// arrows like ▼ ▲ ✓ ⋮ ❮ ❯ ↻ ↩) already render identically across
// platforms since they're basic Unicode punctuation, not multi-color
// emoji glyphs -- converting those to SVG would add files for zero
// visual benefit.
// ---------------------------------------------------------------------------
(function () {
  if (typeof document === 'undefined') return;
  if (document.getElementById('thIconSprite')) return;

  var SPRITE_SVG =
    '<svg id="thIconSprite" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden;" xmlns="http://www.w3.org/2000/svg">' +
    '<defs>' +

    '<symbol id="icon-search" viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5"/><line x1="15.3" y1="15.3" x2="20.5" y2="20.5"/></symbol>' +

    '<symbol id="icon-trash" viewBox="0 0 24 24"><path d="M5 7h14"/><path d="M9 7V4.8c0-.44.36-.8.8-.8h4.4c.44 0 .8.36.8.8V7"/><path d="M7 7l1 13.2c.03.44.4.8.85.8h6.3c.44 0 .82-.36.85-.8L17 7"/><line x1="10" y1="11" x2="10.4" y2="17"/><line x1="14" y1="11" x2="13.6" y2="17"/></symbol>' +

    '<symbol id="icon-camera" viewBox="0 0 24 24"><path d="M4 8.5c0-.83.67-1.5 1.5-1.5H8l1.2-2h5.6l1.2 2h2.5c.83 0 1.5.67 1.5 1.5v9c0 .83-.67 1.5-1.5 1.5h-13c-.83 0-1.5-.67-1.5-1.5z"/><circle cx="12" cy="13" r="3.4"/></symbol>' +

    '<symbol id="icon-chart" viewBox="0 0 24 24"><line x1="4" y1="20" x2="20" y2="20"/><rect x="5.5" y="13" width="3.4" height="7"/><rect x="10.3" y="8" width="3.4" height="12"/><rect x="15.1" y="4.5" width="3.4" height="15.5"/></symbol>' +

    '<symbol id="icon-star" viewBox="0 0 24 24"><path d="M 12.0 2.8 L 14.7 8.28 L 20.75 9.16 L 16.37 13.42 L 17.41 19.44 L 12.0 16.6 L 6.59 19.44 L 7.63 13.42 L 3.25 9.16 L 9.3 8.28 Z"/></symbol>' +
    '<symbol id="icon-star-filled" viewBox="0 0 24 24"><path fill="currentColor" stroke="none" d="M 12.0 2.8 L 14.7 8.28 L 20.75 9.16 L 16.37 13.42 L 17.41 19.44 L 12.0 16.6 L 6.59 19.44 L 7.63 13.42 L 3.25 9.16 L 9.3 8.28 Z"/></symbol>' +

    '<symbol id="icon-wrench" viewBox="0 0 24 24"><path d="M14.7 9.3a4 4 0 0 1-5.4 5.4L4 20l-1-1 5.3-5.3a4 4 0 0 1 5.4-5.4l-2.4 2.4 1.5 1.5z"/></symbol>' +

    '<symbol id="icon-edit" viewBox="0 0 24 24"><path d="M16.5 4.5l3 3L8 19H5v-3z"/></symbol>' +

    '<symbol id="icon-shuffle" viewBox="0 0 24 24"><path d="M3 7h3.5l7 10H20"/><path d="M17 4l3 3-3 3"/><path d="M3 17h3.5l3.2-4.6"/><path d="M17 20l3-3-3-3"/><path d="M11.5 8.6L13.5 5.7"/></symbol>' +

    '<symbol id="icon-bell" viewBox="0 0 24 24"><path d="M6 10a6 6 0 1 1 12 0c0 4 1.5 5.5 1.5 5.5H4.5S6 14 6 10z"/><path d="M10 19.5a2 2 0 0 0 4 0"/></symbol>' +

    '<symbol id="icon-shield" viewBox="0 0 24 24"><path d="M12 3.5l7 2.6v5.4c0 5-3 8-7 9.4-4-1.4-7-4.4-7-9.4V6.1z"/><path d="M9 12l2 2 4-4.2"/></symbol>' +

    '<symbol id="icon-receipt" viewBox="0 0 24 24"><path d="M6 3.5h12v17l-2-1.4-2 1.4-2-1.4-2 1.4-2-1.4-2 1.4z"/><line x1="9" y1="8.5" x2="15" y2="8.5"/><line x1="9" y1="12" x2="15" y2="12"/><line x1="9" y1="15.5" x2="13" y2="15.5"/></symbol>' +

    '<symbol id="icon-map" viewBox="0 0 24 24"><path d="M9 4.5L4 6.5v13l5-2 6 2 5-2v-13l-5 2z"/><line x1="9" y1="4.5" x2="9" y2="17.5"/><line x1="15" y1="6.5" x2="15" y2="19.5"/><circle cx="12" cy="11.5" r="1.3" fill="currentColor" stroke="none"/></symbol>' +

    '<symbol id="icon-scroll" viewBox="0 0 24 24"><rect x="5" y="3.5" width="14" height="17" rx="1.5"/><line x1="8" y1="8" x2="16" y2="8"/><line x1="8" y1="11.5" x2="16" y2="11.5"/><line x1="8" y1="15" x2="13" y2="15"/></symbol>' +

    '<symbol id="icon-calendar" viewBox="0 0 24 24"><rect x="3.5" y="5" width="17" height="15.5" rx="1.5"/><line x1="3.5" y1="9.5" x2="20.5" y2="9.5"/><line x1="8" y1="3" x2="8" y2="7"/><line x1="16" y1="3" x2="16" y2="7"/></symbol>' +

    '<symbol id="icon-dollar" viewBox="0 0 24 24"><text x="12" y="17.5" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="17" font-weight="700" fill="currentColor" stroke="none">$</text></symbol>' +

    '<symbol id="icon-toolbox" viewBox="0 0 24 24"><rect x="3" y="9" width="18" height="10.5" rx="1.5"/><path d="M8 9V6.5c0-.8.7-1.5 1.5-1.5h5c.8 0 1.5.7 1.5 1.5V9"/><line x1="3" y1="13.5" x2="21" y2="13.5"/><line x1="10.5" y1="13.5" x2="10.5" y2="15.5"/><line x1="13.5" y1="13.5" x2="13.5" y2="15.5"/></symbol>' +

    '<symbol id="icon-gear" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3.2"/><path d="M12 3.5v2.3M12 18.2v2.3M20.5 12h-2.3M5.8 12H3.5M18 6l-1.6 1.6M7.6 16.4L6 18M18 18l-1.6-1.6M7.6 7.6L6 6"/></symbol>' +

    '<symbol id="icon-settings" viewBox="0 0 24 24"><line x1="3.5" y1="7" x2="20.5" y2="7"/><circle cx="8.5" cy="7" r="2.3"/><line x1="3.5" y1="12" x2="20.5" y2="12"/><circle cx="16" cy="12" r="2.3"/><line x1="3.5" y1="17" x2="20.5" y2="17"/><circle cx="11" cy="17" r="2.3"/></symbol>' +

    '<symbol id="icon-link" viewBox="0 0 24 24"><rect x="3" y="9" width="9" height="6" rx="3" transform="rotate(-45 7.5 12)"/><rect x="12" y="9" width="9" height="6" rx="3" transform="rotate(-45 16.5 12)"/></symbol>' +

    '<symbol id="icon-clipboard" viewBox="0 0 24 24"><rect x="5" y="4.5" width="14" height="17" rx="1.5"/><rect x="9" y="3" width="6" height="3" rx="1"/><line x1="8" y1="10.5" x2="16" y2="10.5"/><line x1="8" y1="14" x2="16" y2="14"/><line x1="8" y1="17.5" x2="13" y2="17.5"/></symbol>' +

    '<symbol id="icon-warning" viewBox="0 0 24 24"><path d="M12 4l9.5 16.5H2.5z"/><line x1="12" y1="10" x2="12" y2="14.5"/><circle cx="12" cy="17.3" r="0.9" fill="currentColor" stroke="none"/></symbol>' +

    '<symbol id="icon-flask" viewBox="0 0 24 24"><path d="M10 3.5h4"/><path d="M10.5 3.5v6l-5 9c-.6 1.1.2 2.5 1.5 2.5h10c1.3 0 2.1-1.4 1.5-2.5l-5-9v-6"/><line x1="8.5" y1="14.5" x2="15.5" y2="14.5"/></symbol>' +

    '<symbol id="icon-lock" viewBox="0 0 24 24"><rect x="5" y="10.5" width="14" height="9.5" rx="1.5"/><path d="M8 10.5V7.5a4 4 0 0 1 8 0v3"/></symbol>' +

    '<symbol id="icon-rocket" viewBox="0 0 24 24"><path d="M12 2.5c3 2 4.5 5.5 4.5 9.5 0 2-.5 3.7-1.3 5.2h-6.4C8 15.7 7.5 14 7.5 12c0-4 1.5-7.5 4.5-9.5z"/><circle cx="12" cy="10.5" r="1.6"/><path d="M8.8 17.2L6 20.5M15.2 17.2l2.8 3.3"/></symbol>' +

    '<symbol id="icon-note" viewBox="0 0 24 24"><rect x="4.5" y="3.5" width="15" height="17" rx="1.5"/><line x1="8" y1="8" x2="16" y2="8"/><line x1="8" y1="11.5" x2="16" y2="11.5"/><line x1="8" y1="15" x2="12.5" y2="15"/></symbol>' +

    '<symbol id="icon-folder" viewBox="0 0 24 24"><path d="M3.5 6.5c0-.8.7-1.5 1.5-1.5h4l2 2.3h8c.8 0 1.5.7 1.5 1.5v9.7c0 .8-.7 1.5-1.5 1.5H5c-.8 0-1.5-.7-1.5-1.5z"/></symbol>' +

    '<symbol id="icon-bolt" viewBox="0 0 24 24"><path d="M13 2.5L5 14h5.5L11 21.5 19 10h-5.5z"/></symbol>' +

    '<symbol id="icon-signal" viewBox="0 0 24 24"><path d="M4.5 19.5a10.5 10.5 0 0 1 15 0"/><path d="M7.8 16.2a6 6 0 0 1 8.4 0"/><circle cx="12" cy="19.5" r="1.1" fill="currentColor" stroke="none"/></symbol>' +

    '<symbol id="icon-globe" viewBox="0 0 24 24"><circle cx="12" cy="12" r="8.5"/><ellipse cx="12" cy="12" rx="3.5" ry="8.5"/><line x1="3.7" y1="9.5" x2="20.3" y2="9.5"/><line x1="3.7" y1="14.5" x2="20.3" y2="14.5"/></symbol>' +

    '<symbol id="icon-check-circle" viewBox="0 0 24 24"><circle cx="12" cy="12" r="8.5"/><path d="M8 12.3l2.5 2.5 5.5-5.6"/></symbol>' +

    '<symbol id="icon-inbox" viewBox="0 0 24 24"><path d="M4 12.5L6.5 5h11L20 12.5"/><path d="M4 12.5v6c0 .8.7 1.5 1.5 1.5h13c.8 0 1.5-.7 1.5-1.5v-6h-4.8a2.7 2.7 0 0 1-5.4 0z"/></symbol>' +

    '<symbol id="icon-home" viewBox="0 0 24 24"><path d="M4 11.5L12 4l8 7.5"/><path d="M6 10v9.5c0 .8.7 1.5 1.5 1.5h9c.8 0 1.5-.7 1.5-1.5V10"/><path d="M9.5 21v-5.5c0-.55.45-1 1-1h3c.55 0 1 .45 1 1V21"/></symbol>' +

    '<symbol id="icon-terminal" viewBox="0 0 24 24"><rect x="3" y="4.5" width="18" height="15" rx="2"/><path d="M7 9.3l3.3 2.7-3.3 2.7"/><line x1="12" y1="14.7" x2="16.5" y2="14.7"/></symbol>' +

    '<symbol id="icon-book" viewBox="0 0 24 24"><path d="M12 6c-1.9-1.4-4.2-2-6.8-2-.7 0-1.2.6-1.2 1.2v11.6c0 .7.5 1.2 1.2 1.2 2.6 0 4.9.6 6.8 2 1.9-1.4 4.2-2 6.8-2 .7 0 1.2-.5 1.2-1.2V5.2c0-.7-.5-1.2-1.2-1.2-2.6 0-4.9.6-6.8 2z"/><line x1="12" y1="6" x2="12" y2="19"/></symbol>' +

    '<symbol id="icon-first-job" viewBox="0 0 48 48"><rect x="8" y="7" width="26" height="34" rx="3"/><rect x="16" y="4" width="10" height="6" rx="1.5"/><line x1="13" y1="19" x2="29" y2="19"/><line x1="13" y1="25" x2="29" y2="25"/><line x1="13" y1="31" x2="23" y2="31"/><circle cx="35" cy="35" r="8" fill="var(--bg-panel-2)" stroke="#ff8000"/><line x1="35" y1="31.5" x2="35" y2="38.5" stroke="#ff8000"/><line x1="31.5" y1="35" x2="38.5" y2="35" stroke="#ff8000"/></symbol>' +

    '</defs></svg>';

  function injectSprite() {
    document.body.insertAdjacentHTML('afterbegin', SPRITE_SVG);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', injectSprite);
  } else {
    injectSprite();
  }
})();

// ---------------------------------------------------------------------------
// JUMP-NAV SCROLL-SPY -- added 2026-08-16
// Highlights whichever jump-nav pill corresponds to the section currently
// in view, using IntersectionObserver rather than a scroll listener (no
// per-frame math, no debouncing needed, and it naturally handles sections
// of very different heights). Purely additive: pages without a .jump-nav,
// or whose links don't all resolve to an in-page section, are silently
// skipped -- this never assumes a page's structure.
//
// This closes a real inconsistency: the mobile bottom nav and tab buttons
// both had a clear "you are here" treatment, but the jump-nav -- despite
// sitting on every page a person scrolls through -- had none. Reuses the
// same is-active class + orange-accent language as those two so all three
// "current location" indicators in the app now agree with each other.
// ---------------------------------------------------------------------------
(function () {
  if (typeof document === 'undefined' || typeof IntersectionObserver === 'undefined') return;

  function initJumpNavScrollSpy() {
    const nav = document.querySelector('.jump-nav');
    if (!nav) return;

    const links = Array.from(nav.querySelectorAll('a[href^="#"]'));
    const sections = links
      .map(a => ({ link: a, el: document.getElementById(a.getAttribute('href').slice(1)) }))
      .filter(pair => pair.el);
    if (sections.length === 0) return;

    function setActive(id) {
      links.forEach(a => {
        const isMatch = a.getAttribute('href') === '#' + id;
        a.classList.toggle('is-active', isMatch);
        if (isMatch) a.setAttribute('aria-current', 'true'); else a.removeAttribute('aria-current');
      });
    }

    // rootMargin biases the trigger line toward the top of the viewport
    // (just under the sticky header + jump-nav itself) rather than the
    // exact center, so the pill updates right as a section's heading
    // scrolls into that zone -- matching where someone's eye actually is.
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.filter(e => e.isIntersecting);
      if (visible.length === 0) return;
      // If multiple sections are simultaneously in the trigger band
      // (short sections, fast scroll), prefer the one closest to top.
      visible.sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
      setActive(visible[0].target.id);
    }, { rootMargin: '-120px 0px -70% 0px', threshold: 0 });

    sections.forEach(pair => observer.observe(pair.el));
    // Set an initial state immediately rather than waiting for the first
    // scroll/intersection event, so the pill isn't blank on page load.
    setActive(sections[0].el.id);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initJumpNavScrollSpy);
  } else {
    initJumpNavScrollSpy();
  }
})();
